### ISSUE TITLE
Please add a 404 Page

### ISSUE THREAD

**Issue by theriturajps** [saicaca/fuwari#110] opened 2024-06-23 14:42 UTC
**Please add a 404 Page this is very important for the website.**

- [ ] **Request to Add a UI 404 Page**

**Comment by saicaca** [comment] 2024-06-24 17:41
Thanks for your suggestion, will do it later.

**Comment by saicaca** [comment] 2024-06-24 17:42
Duplicate of #36

**Closed** 2024-06-24 17:42 UTC
